variables:
  BDB_PREFIX: $CI_PROJECT_DIR/lib/db4
  BOOST_PREFIX: $CI_PROJECT_DIR/lib/boost
  DEBIAN_FRONTEND: noninteractive

cache:
  key: "$CI_JOB_NAME"
  paths:
  - $BDB_PREFIX
  - $BOOST_PREFIX

build:linux-64:
  image: ubuntu:16.04
  stage: build
  script:
  - ./contrib/gitlab-ci/install-builddeps.sh
  - ./autogen.sh
  - ./configure LDFLAGS="-L${BDB_PREFIX}/lib/ -L${BOOST_PREFIX}/lib/" CPPFLAGS="-I${BDB_PREFIX}/include/ -I${BOOST_PREFIX}/include/"
  - make -j4
  - strip src/eguldend src/egulden-cli src/egulden-tx src/qt/egulden-qt
  artifacts:
    expire_in: 1 week
    paths:
    - src/eguldend
    - src/egulden-cli
    - src/egulden-tx
    - src/qt/egulden-qt
    - src/test/test_egulden
    - src/qt/test/test_egulden-qt

build:linux-32:
  image: 32bit/ubuntu:16.04
  stage: build
  script:
  - ./contrib/gitlab-ci/install-builddeps.sh
  - ./autogen.sh
  - ./configure LDFLAGS="-L${BDB_PREFIX}/lib/" CPPFLAGS="-I${BDB_PREFIX}/include/"
  - make -j2
  - strip src/eguldend src/egulden-cli src/egulden-tx src/qt/egulden-qt
  artifacts:
    expire_in: 1 week
    paths:
    - src/eguldend
    - src/egulden-cli
    - src/egulden-tx
    - src/qt/egulden-qt
    - src/test/test_egulden
    - src/qt/test/test_egulden-qt

test:linux-64:
  image: ubuntu:16.04
  stage: test
  dependencies:
  - build:linux-64
  script:
  - ./src/test/test_egulden
  - ./src/qt/test/test_egulden-qt

test:linux-32:
  image: 32bit/ubuntu:16.04
  stage: test
  dependencies:
  - build:linux-32
  script:
  - ./src/test/test_egulden
  - ./src/qt/test/test_egulden-qt
