variables:
  DEBIAN_FRONTEND: noninteractive

build:linux-64:
  image: ubuntu:16.04
  stage: build
  script:
  - apt-get update
  - apt-get dist-upgrade -y
  - apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
  - apt-get install -y libboost-all-dev
  - apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
  - apt-get install -y software-properties-common
  - add-apt-repository ppa:bitcoin/bitcoin
  - apt-get update
  - apt-get install -y libdb4.8-dev libdb4.8++-dev
  - ./autogen.sh
  - ./configure
  - make -j2
  artifacts:
    expire_in: 1 week
    paths:
    - src/eguldend
    - src/egulden-cli
    - src/egulden-tx
    - src/qt/egulden-qt
    - src/test/test_egulden
    - src/qt/test/test_egulden-qt

build:linux-32:
  image: 32bit/ubuntu:16.04
  stage: build
  script:
  - apt-get update
  - apt-get dist-upgrade -y
  - apt-get install -y build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
  - apt-get install -y libboost-all-dev
  - apt-get install -y libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler
  - apt-get install -y software-properties-common
  - add-apt-repository ppa:bitcoin/bitcoin
  - apt-get update
  - apt-get install -y libdb4.8-dev libdb4.8++-dev
  - ./autogen.sh
  - ./configure
  - make -j2
  artifacts:
    expire_in: 1 week
    paths:
    - src/eguldend
    - src/egulden-cli
    - src/egulden-tx
    - src/qt/egulden-qt
    - src/test/test_egulden
    - src/qt/test/test_egulden-qt

test:linux-64:
  image: ubuntu:16.04
  stage: test
  dependencies:
  - build:linux-64
  script:
  - ./src/test/test_egulden
  - ./src/qt/test/test_egulden-qt

test:linux-32:
  image: 32bit/ubuntu:16.04
  stage: test
  dependencies:
  - build:linux-32
  script:
  - ./src/test/test_egulden
  - ./src/qt/test/test_egulden-qt
