image: debian:stretch

variables:
  BUILD_DEPS: curl ca-certificates build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
  COMMON_DEPS: python python-pip python-dev python-setuptools python-zmq

cache:
  key: "$CI_JOB_NAME"
  paths:
  - depends/

build:linux-64:
  stage: build
  variables:
    HOST: x86_64-unknown-linux-gnu
    PACKAGES: $BUILD_DEPS $COMMON_DEPS bc openjdk-8-jre-headless
  script:
  - apt-get update
  - apt-get install -y --no-install-recommends -qq $PACKAGES
  - cd ./depends
  - make HOST=$HOST -j4
  - cd ..
  - ./autogen.sh
  - ./configure --prefix=`pwd`/depends/$HOST
  - make -j4
  - strip src/eguldend src/egulden-cli src/egulden-tx src/qt/egulden-qt
  artifacts:
    expire_in: 1 week
    paths:
    - src/eguldend
    - src/egulden-cli
    - src/egulden-tx
    - src/qt/egulden-qt
    - src/test/test_egulden
    - src/qt/test/test_egulden-qt

build:linux-32:
  stage: build
  variables:
    HOST: i686-pc-linux-gnu
    PACKAGES: $BUILD_DEPS $COMMON_DEPS g++-multilib bc openjdk-8-jre-headless
  script:
  - apt-get update
  - apt-get install -y --no-install-recommends -qq $PACKAGES
  - cd ./depends
  - make HOST=$HOST -j4
  - cd ..
  - ./autogen.sh
  - ./configure --prefix=`pwd`/depends/$HOST
  - make -j4
  artifacts:
    expire_in: 1 week
    paths:
    - src/eguldend
    - src/egulden-cli
    - src/egulden-tx
    - src/qt/egulden-qt
    - src/test/test_egulden
    - src/qt/test/test_egulden-qt

build:osx:
  stage: build
  variables:
    HOST: x86_64-apple-darwin11
    PACKAGES: $BUILD_DEPS $COMMON_DEPS cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools
  script:
  - apt-get update
  - apt-get install -y --no-install-recommends -qq $PACKAGES
  - pip install ez_setup
  - cd ./depends
  - make HOST=$HOST -j4
  - cd ..
  - ./autogen.sh
  - ./configure --prefix=`pwd`/depends/$HOST
  - make -j4
  artifacts:
    expire_in: 1 week
    paths:
    - src/eguldend
    - src/egulden-cli
    - src/egulden-tx
    - src/qt/egulden-qt
    - src/test/test_egulden
    - src/qt/test/test_egulden-qt

build:win-64:
  stage: build
  variables:
    HOST: x86_64-w64-mingw32
    PACKAGES: $BUILD_DEPS $COMMON_DEPS nsis g++-mingw-w64-x86-64 wine bc openjdk-8-jre-headless
  script:
  - apt-get update
  - apt-get install -y --no-install-recommends -qq $PACKAGES
  - cd ./depends
  - make HOST=$HOST -j4
  - cd ..
  - ./autogen.sh
  - ./configure --prefix=`pwd`/depends/$HOST
  - make -j4
  artifacts:
    expire_in: 1 week
    paths:
    - src/eguldend
    - src/egulden-cli
    - src/egulden-tx
    - src/qt/egulden-qt
    - src/test/test_egulden
    - src/qt/test/test_egulden-qt

test:linux-64:
  stage: test
  dependencies:
  - build:linux-64
  script:
  - ./src/test/test_egulden
  - ./src/qt/test/test_egulden-qt

test:linux-32:
  stage: test
  dependencies:
  - build:linux-32
  script:
  - ./src/test/test_egulden
  - ./src/qt/test/test_egulden-qt
