image: gcc

cache:
  key: "$CI_JOB_NAME"
  paths:
  - depends

build:linux-64:
  stage: build
  variables:
    HOST: x86_64-unknown-linux-gnu
  script:
  - cd ./depends
  - make HOST=$HOST -j4
  - cd ..
  - ./autogen.sh
  - ./configure --prefix=`pwd`/depends/$HOST
  - make -j4
  - strip src/eguldend src/egulden-cli src/egulden-tx src/qt/egulden-qt
  artifacts:
    expire_in: 1 week
    paths:
    - src/eguldend
    - src/egulden-cli
    - src/egulden-tx
    - src/qt/egulden-qt
    - src/test/test_egulden
    - src/qt/test/test_egulden-qt

build:linux-32:
  stage: build
  variables:
    HOST: i686-pc-linux-gnu
  script:
  - cd ./depends
  - make HOST=$HOST -j4
  - cd ..
  - ./autogen.sh
  - ./configure --prefix=`pwd`/depends/$HOST
  - make -j4
  artifacts:
    expire_in: 1 week
    paths:
    - src/eguldend
    - src/egulden-cli
    - src/egulden-tx
    - src/qt/egulden-qt
    - src/test/test_egulden
    - src/qt/test/test_egulden-qt

build:osx:
  stage: build
  variables:
    HOST: x86_64-apple-darwin11
  script:
  - cd ./depends
  - make HOST=$HOST -j4
  - cd ..
  - ./autogen.sh
  - ./configure --prefix=`pwd`/depends/$HOST
  - make -j4
  artifacts:
    expire_in: 1 week
    paths:
    - src/eguldend
    - src/egulden-cli
    - src/egulden-tx
    - src/qt/egulden-qt
    - src/test/test_egulden
    - src/qt/test/test_egulden-qt

test:linux-64:
  stage: test
  dependencies:
  - build:linux-64
  script:
  - ./src/test/test_egulden
  - ./src/qt/test/test_egulden-qt

test:linux-32:
  stage: test
  dependencies:
  - build:linux-32
  script:
  - ./src/test/test_egulden
  - ./src/qt/test/test_egulden-qt
